### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by jcutrell** [Whiteboard/launchframe#7]
Let's use this thread to talk about what's coming next for Launchframe.
- YAML-driven config to allow launchframe to be used in WordPress, Rails, or Static
- jQuery: going opt-in
- Remove dependencies
  - Remove parts of Bootstrap by default
  - Go to Flexbox by default

**Comment by ptcrt** [comment]
- Integrate Webpack.
- Switch from NPM to Yarn.
- Simplify Bootstrap. Import only grid and grid helpers.
